 
 --CREATE DATABASE	dbSistema_Ventas
 --GO

 USE dbSistema_Ventas
 GO

 --ROL
CREATE TABLE ROL(
IdRol INT PRIMARY KEY IDENTITY,
Descripcion VARCHAR(50),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

--PERMISOS
CREATE TABLE PERMISOS(
IdPermiso INT PRIMARY KEY IDENTITY,
IdRol INT REFERENCES ROL(IdRol),
NombreMenu VARCHAR(100),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

--PROVEEDOR
CREATE TABLE PROVEEDOR(
IdProveedor INT PRIMARY KEY IDENTITY,
Documento VARCHAR(50),
RazonSocial VARCHAR(50), 
Correo VARCHAR(50),
Telefono VARCHAR(50),
Estado Bit,
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO


--CLIENTE
CREATE TABLE CLIENTE(
IdCliente INT PRIMARY KEY IDENTITY,
Documento VARCHAR(50),
NombreCompleto VARCHAR(50),
Correo VARCHAR(50),
Telefono VARCHAR(50),
Estado Bit,
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO


--USUARIO
CREATE TABLE USUARIO(
IdUsuario INT PRIMARY KEY IDENTITY,
Documento VARCHAR(50), 
NombreCompleto VARCHAR(50), 
Correo VARCHAR(50),
Clave VARCHAR(50),
IdRol INT REFERENCES ROL(IdRol),
Estado Bit,
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO


--COMPRA
CREATE TABLE COMPRA(
IdCompra INT PRIMARY KEY IDENTITY,
IdUsuario INT REFERENCES USUARIO(IdUsuario),
IdProveedor INT REFERENCES PROVEEDOR(IdProveedor),
TipoFactura VARCHAR(50),
NumeroFactura VARCHAR(50),
MontoTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

--CATEGORIA
CREATE TABLE CATEGORIA(
IdCategoria INT PRIMARY KEY IDENTITY,
Descripcion VARCHAR(100),
Estado Bit,
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

--PRODUCTO
CREATE TABLE PRODUCTO(
IdProducto INT PRIMARY KEY IDENTITY,
Codigo VARCHAR(50),
Nombre VARCHAR(50),
Descripcion VARCHAR(100),
IdCategoria INT REFERENCES CATEGORIA(IdCategoria),
Stock INT NOT NULL DEFAULT 0,
PrecioCompra DECIMAL(10,2) DEFAULT 0,
PrecioVenta DECIMAL(10,2) DEFAULT 0,
Estado Bit,
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO


--DETALLE_COMPRA
CREATE TABLE DETALLE_COMPRA(
IdDetalleCompra INT PRIMARY KEY IDENTITY,
IdCompra INT REFERENCES COMPRA(IdCompra),
IdProducto INT REFERENCES PRODUCTO(IdProducto),
PrecioCompra DECIMAL(10,2) DEFAULT 0, --HistorialDeUltimoPrecioCompra
PrecioVenta DECIMAL(10,2) DEFAULT 0, --HistorialDeUltimoPrecioVenta
Cantidad INT,
MontoTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO


--VENTA
CREATE TABLE VENTA(
IdVenta INT PRIMARY KEY IDENTITY,
IdUsuario INT REFERENCES USUARIO(IdUsuario),
TipoFactura VARCHAR(50),
NumeroFactura VARCHAR(50),
DocumentoCliente VARCHAR(50),
NombreCliente VARCHAR(50),
MontoPago DECIMAL(10,2),
MontoCambio DECIMAL(10,2),
MontoTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

--DETALE_VENTA
CREATE TABLE DETALE_VENTA(
IdDetalleVenta INT PRIMARY KEY IDENTITY,
IdVenta INT REFERENCES VENTA(IdVenta),
IdProdcuto INT REFERENCES PRODUCTO(IdProducto),
PrecioVenta DECIMAL(10,2),
Cantidad INT,
SubTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO
